DEBUG = False
TEMPLATE_DEBUG = DEBUG
ADMINS = (('Admin',''),)
MANAGERS = ADMINS

DATABASE_ENGINE = ''
DATABASE_NAME = ''
DATABASE_USER = ''
DATABASE_PASSWORD = ''
DATABASE_HOST = ''
DATABASE_PORT = ''

PREPEND_WWW = True
TIME_ZONE = 'America/Chicago'
LANGUAGE_CODE = 'en-us'
USE_I18N = False

MEDIA_ROOT = ''
MEDIA_URL = ''
BLOG_FEED_URL = ''
